# Generated by Django 2.1.7 on 2019-05-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interview_Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('interview_code', models.ManyToManyField(related_name='面试授权', to='backend.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_code', models.CharField(max_length=5)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('interview_code', models.ManyToManyField(related_name='问题', to='backend.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_code', models.CharField(max_length=5)),
                ('url', models.CharField(max_length=255)),
                ('beauty', models.IntegerField()),
                ('emotion', models.IntegerField()),
                ('affinity', models.IntegerField()),
                ('admin', models.ManyToManyField(related_name='面试官信息', to='backend.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('actual_name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_code', models.CharField(max_length=5)),
                ('url', models.CharField(max_length=255)),
                ('beauty', models.IntegerField(blank=True, null=True)),
                ('emotion', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='求职者信息', to='backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='求职者成绩', to='backend.User'),
        ),
    ]
