# Generated by Django 2.1.7 on 2019-05-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview_authority',
            old_name='interview_code',
            new_name='interview',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='interview_code',
            new_name='interview',
        ),
    ]
