# Generated by Django 2.1.7 on 2019-05-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190519_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train_video',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='video',
            name='emotion',
        ),
        migrations.AddField(
            model_name='train_video',
            name='smile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='smile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='admit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='train_video',
            name='affinity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='train_video',
            name='beauty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='beauty',
            field=models.IntegerField(default=0),
        ),
    ]
