# Generated by Django 2.1.7 on 2019-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190521_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='user',
        ),
        migrations.AddField(
            model_name='performance',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
