# Generated by Django 2.1.7 on 2019-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='beauty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='smile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
