# Generated by Django 2.1.7 on 2019-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_video_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='expire',
            field=models.BooleanField(default=False),
        ),
    ]
