# Generated by Django 2.1.7 on 2019-06-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_interview_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='求职者', to='backend.User'),
        ),
    ]
