# Generated by Django 2.1.7 on 2019-06-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_performance_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='use',
            new_name='user',
        ),
    ]
